version: "3.8"
services:
  post_db:
    image: postgres:latest
    container_name: post_postgres
    restart: always
    env_file:
      - ./.env.dev


  post_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    depends_on:
      - post_db
    volumes:
    - ./coverage_reports:/work/coverage_reports
    